// Code generated by Kitex v0.5.1. DO NOT EDIT.

package goworkflowservice

import (
	server "github.com/cloudwego/kitex/server"
	go_workflow "github.com/hexudonghj/go_workflow/kitex_gen/go_workflow"
)

// NewInvoker creates a server.Invoker with the given handler and options.
func NewInvoker(handler go_workflow.GoWorkflowService, opts ...server.Option) server.Invoker {
	var options []server.Option

	options = append(options, opts...)

	s := server.NewInvoker(options...)
	if err := s.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	if err := s.Init(); err != nil {
		panic(err)
	}
	return s
}
