// Code generated by Kitex v0.5.1. DO NOT EDIT.
package goworkflowservice

import (
	server "github.com/cloudwego/kitex/server"
	go_workflow "github.com/hexudonghj/go_workflow/kitex_gen/go_workflow"
)

// NewServer creates a server.Server with the given handler and options.
func NewServer(handler go_workflow.GoWorkflowService, opts ...server.Option) server.Server {
	var options []server.Option

	options = append(options, opts...)

	svr := server.NewServer(options...)
	if err := svr.RegisterService(serviceInfo(), handler); err != nil {
		panic(err)
	}
	return svr
}
