// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameActHiProcinst = "act_hi_procinst"

// ActHiProcinst mapped from table <act_hi_procinst>
type ActHiProcinst struct {
	ID          int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`       // 自增主键ID
	ProcInstID  string    `gorm:"column:proc_inst_id;not null" json:"proc_inst_id"`        // 流程实例ID
	ProcDefID   string    `gorm:"column:proc_def_id;not null" json:"proc_def_id"`          // 流程定义ID
	StartTime   int64     `gorm:"column:start_time;not null;default:-1" json:"start_time"` // 流程开始时间
	EndTime     int64     `gorm:"column:end_time;not null;default:-1" json:"end_time"`     // 流程结束时间（如果流程未结束则为-1）
	StartUserID string    `gorm:"column:start_user_id;not null" json:"start_user_id"`      // 流程发起人ID
	Status      string    `gorm:"column:status;not null" json:"status"`                    // 流程状态
	TenantID    string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	CreateTime  time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 数据创建时间
	UpdateTime  time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 数据更新时间
}

// TableName ActHiProcinst's table name
func (*ActHiProcinst) TableName() string {
	return TableNameActHiProcinst
}
