// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package entity

import (
	"time"
)

const TableNameActReProcdef = "act_re_procdef"

// ActReProcdef mapped from table <act_re_procdef>
type ActReProcdef struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"` // 自增主键
	ProcDefID  string    `gorm:"column:proc_def_id;not null" json:"proc_def_id"`    // 流程定义ID
	ProcDefKey string    `gorm:"column:proc_def_key;not null" json:"proc_def_key"`  // 流程定义KEY
	Name       string    `gorm:"column:name;not null" json:"name"`                  // 流程名称
	Version    int32     `gorm:"column:version;not null" json:"version"`            // 流程版本号
	Resource   string    `gorm:"column:resource" json:"resource"`                   // 流程定义资源
	TenantID   string    `gorm:"column:tenant_id;not null" json:"tenant_id"`        // 租户ID
	UserID     string    `gorm:"column:user_id;not null;default:流程所属用户ID" json:"user_id"`
	DeployTime int64     `gorm:"column:deploy_time;not null;default:-1" json:"deploy_time"`                // 流程部署时间
	CreateTime time.Time `gorm:"column:create_time;not null;default:CURRENT_TIMESTAMP" json:"create_time"` // 数据创建时间
	UpdateTime time.Time `gorm:"column:update_time;not null;default:CURRENT_TIMESTAMP" json:"update_time"` // 流程更新时间
}

// TableName ActReProcdef's table name
func (*ActReProcdef) TableName() string {
	return TableNameActReProcdef
}
